name: FartingSquid
main: net.dasigns.fartingsquid.FartingSquid
version: ${version}
authors: [Dakota628]
commands:
   fartingsquid:
      description: Spawns a farting squid for you to ride.
      usage: /fartingsquid
permissions:
    fartingsquid.spawn:
        description: Gives you access to spawning a fartingsquid
        default: op